project:
  type: website
  output-dir: docs

website:
  title: "SDS291"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: https://docs.google.com/spreadsheets/d/148AKHY_3sfFzWpG17-OkK2TiI5QiCSd9whtTZPhfKt0/edit?usp=sharing
        text: Course Schedule
      - href: homework.qmd
        text: Homework
      - href: https://docs.google.com/document/d/13MWHuISh_i8Bj4jUWXJlyWMAq0ZbVjXN/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
        text: Final Project Guide
      - text: Trouble shooting links
        menu:
        - href: https://smithcollege-sds.github.io/sds100/lab_01_setup.html
          text: Downloading R and RStudio
        - text: Basics of Data Wranging in R
          href: https://smithcollege-sds.github.io/sds100/lab_04_wrangling.html
        - text: Troubleshooting Quarto
          href: https://smithcollege-sds.github.io/sds-www/rmarkdown_problems.html
      - text: Lecture Slides
        menu:
        - href: https://docs.google.com/presentation/d/1UEmngV8WZov1wvq02FtvjDwalBjIGdyv/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Welcome Slides
        - href: https://docs.google.com/presentation/d/1DmSHbEVhmmIetIwcD3YCX54kqBj_26LS/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 2 Slides- Simple Regression
        - href: https://docs.google.com/presentation/d/1NTJm935dGekJlUC_zdj2266xIEbwcv6_/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 3 Slides- Regression Conditions
        - href: https://docs.google.com/presentation/d/1OibpmC7CCYrGnkdJ1VgHxbRw2bi8QKth/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 4 Slides- Transformation, Conditions, and Inference  
        - href: https://docs.google.com/presentation/d/1XXCTMaA49E8xQqjs28dF_8HEq-TSS_XM/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 5 Slides- Wrapping Up Simple Regression   
        - href: https://docs.google.com/presentation/d/1fKX0FjtpH0P7ILIseUFsOW3-nYz30b1w/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 6 Slides- Multiple Regression 1 
        - href: https://docs.google.com/presentation/d/1hTZuCJhqWXKieIWyZGdaEWCiUHL7xA7u/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 7 Slides- Multiple Regression 2
        - href: https://docs.google.com/presentation/d/1lxk_TFBVqNitKJ8PHXWhdfx7IWXhMcHI/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 8 Slides- Multiple Regression 3  
        - href: https://docs.google.com/presentation/d/1n-4uTCoQmuebVYLpABhkXBca8_A5gOSr/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 9 Slides- Multiple Regression 4    
        - href: https://docs.google.com/presentation/d/1r5dchgbh0egrf7TWUn3IvO2yuAiqfeIh/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 10 Slides- Goodness of fit and Model Selection  
        - href: https://docs.google.com/presentation/d/1vW47CeCUIB3x_PqTQLWRlTcfqH5cAZ15/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 11 Slides- Logistic Regression
        - href: https://docs.google.com/presentation/d/1-2e4gjkkgysUNo5HbXRe81ui6X3qwRUR/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 13 Slides- Logistic Regression 2
        - href: https://docs.google.com/presentation/d/10EXvKnpZNDrZLCLIh6zffJddBOdPcBPq/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 14 Slides- Logistic Regression 3 and time series
        - href: https://docs.google.com/presentation/d/149esKumch0chEAYhGhpTcqh92bDuPezz/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 15 Wrapping Up
      - text: Sample Code and R- Activities
        href: sample_code.qmd

  

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true
    code-background: true


editor: visual

