project:
  type: website
  output-dir: docs

website:
  title: "SDS291"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: homework.qmd
        text: Homework
      - text: Trouble shooting links
        menu:
        - href: https://smithcollege-sds.github.io/sds100/lab_01_setup.html
          text: Downloading R and RStudio
        - text: Basics of Data Wranging in R
          href: https://smithcollege-sds.github.io/sds100/lab_04_wrangling.html
        - text: Troubleshooting Quarto
          href: https://smithcollege-sds.github.io/sds-www/rmarkdown_problems.html
      - text: Lecture Slides
        menu:
        - href: lectures/welcome.pptx
          text: Intro Slides
      - text: Sample Code
        href: sample_code.qmd
  

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

