project:
  type: website
  output-dir: docs

website:
  title: "SDS291"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: https://docs.google.com/spreadsheets/d/148AKHY_3sfFzWpG17-OkK2TiI5QiCSd9whtTZPhfKt0/edit?usp=sharing
        text: Course Schedule
      - href: homework.qmd
        text: Homework
      - href: https://docs.google.com/document/d/13MWHuISh_i8Bj4jUWXJlyWMAq0ZbVjXN/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
        text: Final Project Guide
      - text: Trouble shooting links
        menu:
        - href: https://smithcollege-sds.github.io/sds100/lab_01_setup.html
          text: Downloading R and RStudio
        - text: Basics of Data Wranging in R
          href: https://smithcollege-sds.github.io/sds100/lab_04_wrangling.html
        - text: Troubleshooting Quarto
          href: https://smithcollege-sds.github.io/sds-www/rmarkdown_problems.html
      - text: Lecture Slides
        menu:
        - href: https://docs.google.com/presentation/d/1UEmngV8WZov1wvq02FtvjDwalBjIGdyv/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Welcome Slides
        - href: https://docs.google.com/presentation/d/1DmSHbEVhmmIetIwcD3YCX54kqBj_26LS/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 2 Slides- Simple Regression
        - href: https://docs.google.com/presentation/d/1NTJm935dGekJlUC_zdj2266xIEbwcv6_/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 3 Slides- Regression Conditions
      - text: Sample Code and R- Activities
        href: sample_code.qmd

  

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

