---
title: "Homeworks"
editor: visual
---

All homeworks are due at 11:59 PM on the following Friday after they are assigned (all numbers indicate Stat2 exercises at the end of the chapter. Homeworks must be submitted as both a .RMD and .PDF. I've created a template you are free to download for homeworks following [this link](https://drive.google.com/file/d/1LF4cuvVVtX0KsNvQTVuvkAREP5EC-nON/view?usp=sharing), but you are free to use your own.

0.  Due Friday, September 15th:
    -   0.6, 0.8, , 0.9, 0.16
1.  Due Friday, September 22nd:
    -   1.1, 1.3, 1.13, 1.14
    -   Q5: In your own words, describe what it means to have non-constant variance.
    -   Q6: In your own words, what is the difference between the t-distribution and z (standard normal) and why does it matter for calculating p-values?
    -   Q7: What is the null hypothesis for a simple regression?
2.  Due Friday, September 29th
    -   1.4, 1.8, 1.10
    -   1.16 (you will need to load the package `Stat2Data` in a chunk of code, plus include the code `data(GlowWorms)` to pull up the dataset after loading the package- note that the dataset name is wrong in the textbook use GlowWorms as the data name)
    -   1.18, 1.19
3.  Due Friday, October 6th
    -   Regression practice- combined with in class R Time
    -   Read and complete [R Activity for Homework 3](inclass_r/activity_r2.html)
4.  Due Friday, October 13th- **Case Study 1**
    -   General Guidelines for [Case Studies](inclass_r/case-study-guidelines.pdf)
    -   [Case Study 1 Instructions](inclass_r/case_study_1.pdf)
    -   Template [QMD File](https://drive.google.com/file/d/1ar46GoIDPMH05bI5l5jfYQLlOjFfgKwC/view?usp=sharing)
5.  Due Friday, October 20th
    -   2.18, 2.21, 2.22, 2.35, 3.2, 3.17 (**pay attention to the sample size and confidence level**), 3.26
6.  Due Friday, November 10th
    -   [Case Study 2 Instructions](inclass_r/case_study_2.pdf)

7. Due Friday, November 17th
    - 4.2 (a & b only), 4.7, 4.8, 4.9, 4.20 (a-d only)
    - see sample code below for splitting up the data for 4.8
```{r, eval=F}
data(CountyHealth)

train = CountyHealth[1:35,]
test =CountyHealth[36:53,]
```
  
7. Due December 1st
    - 9.1, 9.3, 9.11, 9.21, 9.22, 9.39
    
6.  Due Thursday, December14th
    -   [Case Study 3](inclass_r/case_study_3.qmd)
