---
title: "Sample R Code and R Activities"
---

The following links will take you to R code and data used for class or lecture.

# Week 2 and 3 - Simple Linear Regression

1.  [simple_regression.qmd](https://drive.google.com/file/d/1L1tNpKcMumnlCdxaUBUoFXYeBlrvw9u5/view?usp=sharing)

2.  Due Sunday, Sept 17th by 11:59 PM on Moodle: Read and complete [this R-Activity #1](inclass_r/activity_r.html)


# Week 4- Regression Conditions and Transformation

1. [Code used for lecture slides](https://drive.google.com/file/d/1OmCwmijAQ3dOvw2WSkGXmPZPnKzMBC41/view?usp=sharing)


# Week 5- Wrapping up Simple Regression and Intro to Multiple Regression

1. [Code used for lecture slides](https://drive.google.com/file/d/1XY5ELk_NqsEEKFHBUqr8KgcizcZ7mtl2/view?usp=sharing)

# Week 6- Multiple Regression
1. [Intro to Multiple Regression](https://drive.google.com/file/d/1YwTTmpd57JAfKSgLSOTDjOAPKPc_Blez/view?usp=sharing)

# Week 7- Multiple Regression 2

1. [Practice with Interactions](https://drive.google.com/file/d/1hTSz4Yj9fk7wOeD9yG7WRqbh3hjHZjJW/view?usp=sharing)

2. **Due Sunday October 22nd**[In-Class R Activity 2](inclass_r/in_class_r_2.html) 

3. **Mid-term List of Concepts** [here](lectures/Midterm_list_of_concepts.docx)


# Week 8- Multiple Regression 3
1. [Multiple Regression 3](https://drive.google.com/file/d/1lnrrq_evhbdccWDl3Tao7UulNqRTc1ZR/view?usp=sharing)

# Week 9- Randomization and Bootstrapping

1. [sample code](https://drive.google.com/file/d/1n2kaG21glbHVlGNG7F6oRJ0cfHR4wUVA/view?usp=sharing)


# Week 10- Goodness of fit and model selection

1. [Making Regression Tables/Summary Stats](https://drive.google.com/file/d/103v77qS8gIFSnCDYen7-IppLwImMnzu9/view?usp=sharing)


2. [Week 10 Sample Code](https://drive.google.com/file/d/1rW-EDuhCr9siKkQqITxMTpmXz9DMzIhg/view?usp=sharing)

# Week 11- Logistic Regression

1. [sample code](https://drive.google.com/file/d/1vATT0F2Tkk9QGYHH7igQt2hpdbUNRef6/view?usp=sharing)


# Week 12- Citations

1. [sample code](https://drive.google.com/file/d/1xPtd0e1C3azcED-v7L4YBGDUct57-pnp/view?usp=sharing) 

2. [Bib-Tex File](https://drive.google.com/file/d/1xQCrT8zeyaeCtx7prTSikkLRV1FiP6zg/view?usp=sharing)

3. **Exam 2 List of Concepts** [here](lectures/Exam2_concepts.docx)


# Week 13- Logistic Regression Continued

1. [sample code](https://drive.google.com/file/d/19uLJNk67WKFKunIG5vplobjmU5eDQZFo/view?usp=sharing)

2. [Review Session Code](https://drive.google.com/file/d/105osTEG06VwNM4R0y_JQdQZLK1wjfeso/view?usp=sharing)



